export const PLANS = [
  {
    id: "weekly",
    name: "Weekly",
    price: "USD 19",
    priceKES: "KES 2470",
    whopPlanId: "plan_zDNVM2Xuxd3vG",
    whopCheckoutUrl: "https://whop.com/checkout/plan_zDNVM2Xuxd3vG",
    usd: 19,
    kes: 2470,
    period: "/week",
    duration: 7,
    features: [
      "Trusted by 10,000+ traders",
      "Access to the Indicator",
      "Access to Video Guides",
      "Regular indicator updates",
      "Full support from our team",
      "Cancel at any time",
    ],
    benefits: [
      "Perfect for testing our service",
      "No long-term commitment",
      "Full signal access during trial",
      "Email support available",
    ],
    popular: false,
  },
  {
    id: "monthly",
    name: "Monthly",
    price: "USD 49",
    priceKES: "KES 6370",
    whopPlanId: "plan_Q3SBTQdA2p6Nt",
    whopCheckoutUrl: "https://whop.com/checkout/plan_Q3SBTQdA2p6Nt",
    usd: 49,
    kes: 6370,
    period: "/month",
    duration: 30,
    features: [
      "Save 37% vs monthly",
      "Trusted by 12,000+ traders",
      "Access to the Indicator",
      "Access to Video Guides",
      "Regular indicator updates",
      "Full support from our team",
      "Cancel at any time",
    ],
    benefits: [
      "Most popular choice",
      "Best value for active traders",
      "Priority customer support",
      "Advanced AI analysis included",
      "All premium features unlocked",
    ],
    popular: true,
  },
  {
    id: "quarterly",
    name: "Quarterly",
    price: "USD 129",
    priceKES: "KES 16770",
    whopPlanId: "plan_0ekL4yNSd5mRh",
    whopCheckoutUrl: "https://whop.com/checkout/plan_0ekL4yNSd5mRh",
    usd: 129,
    kes: 16770,
    period: "/quarterly",
    duration: 90,
    features: [
      "Only Pay Once",
      "Trusted by 12,000+ traders",
      "Access to the Indicator",
      "Access to Video Guides",
      "Regular indicator updates",
      "Priority support from our team",
      "Cancel at any time",
    ],
    benefits: [
      "Best value for serious traders",
      "Extended commitment = better results",
      "Priority customer support",
      "All premium features included",
      "Save money vs monthly billing",
    ],
    popular: false,
  },
];